import { AiNotice } from "../../../../src/shared/components/AiNotice";
import type { AiNoticeVariant } from "../../../../src/shared/components/AiNotice";
import { notesIn, renderMarkup } from "../../../helpers/staticMarkup";

// The owner's approved copy of 2026-09-25. These strings are the disclosure
// itself, so a changed word must fail here and go back to the owner.
const APPROVED_COPY: Record<AiNoticeVariant, string> = {
  session:
    "Story text and images in this game are generated by AI as you play.",
  kids: "This story is written by an AI. That's a computer program, not a real person. It can make mistakes.",
  reminder:
    "Reminder: this story is generated by an AI system, not written by a person.",
  join: "This story is written by an AI system, not a person. Your choices steer what it writes next.",
  setup:
    "An AI system will write your story and create its images from your premise.",
};

describe("AiNotice", () => {
  it.each(Object.entries(APPROVED_COPY) as [AiNoticeVariant, string][])(
    "renders the %s notice as an English note named AI system, with the approved text",
    (variant, copy) => {
      const html = renderMarkup(<AiNotice variant={variant} />);

      expect(notesIn(html)).toEqual([
        { name: "AI system", lang: "en", text: copy, offset: 0 },
      ]);
    }
  );

  it("shows the AI badge as visible text", () => {
    const html = renderMarkup(<AiNotice variant="session" />);

    expect(html).toMatch(/<span aria-hidden="true"[^>]*>AI<\/span>/);
  });
});
