import {
  LandingSection,
  LandingBenefit,
  LandingHero,
  // LandingTestimonialCarousel,
  LandingFAQ,
  LandingProcess,
  Footer,
} from "../components";

export function ForStorytellers() {
  const benefits = [
    {
      imageSrc: "/landing/time-passes2.jpeg",
      title: "You Want to Create Quickly, Not Write Forever",
      description:
        "Stop wrestling with endless branching narratives. Define your World's essence, use our AI Worldbuilding Assistant to flesh out details, and test ideas in minutes. Focus on the big picture.",
    },
    {
      imageSrc: "/landing/fast-iteration2.jpeg",
      title: "You Need Detailed Control Over Your World",
      description:
        "Fine-tune every aspect: characters, locations, conflicts, mechanics, pacing, tone, and possible endings. Set precise rules for how stories unfold to create the experience you envision.",
    },
    {
      imageSrc: "/landing/multiplayer2.jpeg",
      title: "You Want Multiplayer Without the Headache",
      description:
        "Our AI handles the narrative while our infrastructure manages the delivery. No complex story trees, no server setup, no programming — just collaborative storytelling that works.",
    },
  ];

  // const testimonials = [
  //   {
  //     quote:
  //       "I spent months trying to write a branching narrative in Twine. With Chosen Path, I created something better in an afternoon. The AI understands my World and generates content that feels authentically mine.",
  //     author: "Sarah Chen",
  //     role: "Interactive Fiction Author",
  //   },
  //   {
  //     quote:
  //       "As a game designer, I was skeptical about AI-generated content. But this isn't just generation—it's a true collaboration. I set the rules, the engine brings them to life.",
  //     author: "Marcus Rivera",
  //     role: "Indie Game Developer",
  //   },
  // ];

  const process = [
    {
      number: 1,
      title: "Draft Your Initial World",
      description:
        "Create an initial draft of a story World based on a vision or idea. Start with a simple prompt or detailed specifications.",
      imageSrc: "/academy/story-engine.jpeg",
    },
    {
      number: 2,
      title: "Flesh Out the Details",
      description:
        "Develop characters, locations, conflicts, mechanics, and more — either manually or by giving instructions to the AI Worldbuilding Assistant.",
      imageSrc: "/academy/setting.jpeg",
    },
    {
      number: 3,
      title: "Let Players Explore",
      description:
        "Share your World and watch as unique stories emerge. The engine handles prose, choices, and multiplayer coordination for you.",
      imageSrc: "/academy/switches-threads.jpeg",
    },
  ];

  const faqs = [
    {
      question: "How is this different from other interactive fiction tools?",
      answer:
        "Traditional tools require you to write every possible path and outcome. Chosen Path uses AI to generate dynamic narratives based on the World you define. You create the framework; the engine creates unlimited unique stories within it.\n\nUnlike simple AI writing assistants or custom GPTs, Chosen Path is a fully-fledged story engine designed specifically for interactive fiction. It can handle complex World mechanics, multiplayer coordination, character consistency across sessions, and intricate rule systems that other AI tools simply can't manage.",
    },
    {
      question: "Do I need programming experience?",
      answer:
        "Not at all! Our interface is designed for storytellers, not programmers. If you can describe your World and its rules in plain language, you can create with Chosen Path.",
    },
    {
      question: "Who owns the content I create?",
      answer:
        "You retain full ownership of the World elements that you personally create — your characters, settings, plot concepts, rules, and creative vision.\n\nHowever, content generated by AI (whether through the Worldbuilding Assistant or during gameplay) cannot have copyright protection and automatically belongs to the public domain. This includes AI-generated story text, character dialogue, and narrative developments that emerge during player sessions.",
    },
    {
      question: "Can I monetize my story Worlds?",
      answer:
        "Chosen Path is not currently incorporated as a company. We're considering establishing a business structure that would allow creators to monetize their stories, but this capability doesn't exist yet.\n\nIf you're interested in helping turn Chosen Path into a company that supports creator monetization, please reach out to us!",
    },
    {
      question: "What if the AI generates something inappropriate?",
      answer:
        "You control the tone and content boundaries of your World. Our content filters and your World's rules work together to ensure appropriate content generation.",
    },
  ];

  return (
    <div className="max-w-2xl mx-auto p-4 font-lora">
      <LandingHero
        headline="Create Living Story Worlds in Minutes, Not Months"
        subheadline="Chosen Path is a story engine for interactive fiction creators. Define rich Worlds with characters, conflicts, and mechanics — then let AI bring them to life based on your creative vision."
        ctaPrimary={{
          text: "Start Creating",
          link: "/users/signin",
        }}
        ctaSecondary={{
          text: "Learn More",
          link: "/academy/story-engine-not-writing-tool",
        }}
      />

      <div className="grid md:grid-cols-3 gap-6 md:gap-4 mb-12">
        {benefits.map((benefit, index) => (
          <LandingBenefit key={index} {...benefit} />
        ))}
      </div>

      {/* <LandingSection title="Trusted by Storytellers">
        <LandingTestimonialCarousel testimonials={testimonials} />
      </LandingSection> */}

      <LandingSection title="How It Works">
        <LandingProcess steps={process} />
      </LandingSection>

      <LandingSection title="Frequently Asked Questions">
        <LandingFAQ items={faqs} />
      </LandingSection>

      <LandingSection title="Ready to Create Your First World?">
        <div className="bg-primary-50 p-8 rounded-lg">
          <p className="text-xl mb-6 text-primary-700">
            Join our beta and create interactive experiences for free.
          </p>
          <div className="flex flex-col sm:flex-row gap-4">
            <a
              href="/users/signin"
              className="inline-block bg-accent text-white px-8 py-3 rounded-lg font-semibold hover:bg-accent-dark transition-colors"
            >
              Start Creating
            </a>
            <a
              href="/academy/story-engine-not-writing-tool"
              className="inline-block bg-white text-primary-700 px-8 py-3 rounded-lg font-semibold border border-primary-200 hover:bg-primary-50 transition-colors"
            >
              Learn More
            </a>
          </div>
        </div>
      </LandingSection>

      <Footer />
    </div>
  );
}
