import type { Beat, ClientStoryState } from "core/types";
import { StoryDisplay } from "../../../../src/game/components/StoryDisplay";
import { GameSessionContext } from "../../../../src/game/GameSessionContext";
import { useStoryBeatState } from "../../../../src/game/hooks/useStoryBeatState";
import { notesIn, renderMarkup } from "../../../helpers/staticMarkup";
import {
  beat,
  clientStoryState,
  gameSession,
  player,
} from "../../../helpers/storyFixtures";

// The beat navigation state is set by effects, which a static render never
// runs; each test sets it to a state the real hook reaches. The beat itself
// is a marker, so the tests can check what the notice sits above.
jest.mock("../../../../src/game/hooks/useStoryBeatState", () => ({
  useStoryBeatState: jest.fn(),
}));
jest.mock("../../../../src/game/components/BeatContent", () => ({
  BeatContent: ({ currentBeat }: { currentBeat: Beat | null }) =>
    `[beat: ${currentBeat?.title ?? "none"}]`,
}));
jest.mock("../../../../src/game/components/NextBeatPlaceholder", () => ({
  NextBeatPlaceholder: () => "[next beat is being written]",
}));

const SESSION =
  "Story text and images in this game are generated by AI as you play.";
const KIDS =
  "This story is written by an AI. That's a computer program, not a real person. It can make mistakes.";
const REMINDER =
  "Reminder: this story is generated by an AI system, not written by a person.";

/**
 * A static render mounts the story view afresh, so the beats passed here are
 * the ones the session opened with.
 */
function renderStory(
  beats: Beat[],
  displayedBeatIndex: number | null,
  overrides: Partial<ClientStoryState> = {}
): string {
  jest.mocked(useStoryBeatState).mockReturnValue({
    displayedBeatIndex,
    showNextBeatPlaceholder: displayedBeatIndex === beats.length,
    localSelectedChoice: undefined,
    beatHistory: beats,
    isViewingLatestBeat: displayedBeatIndex === beats.length - 1,
    latestBeat: beats[beats.length - 1] ?? null,
    navigateToBeat: jest.fn(),
    handleChoiceSelected: jest.fn(),
    resetChoice: jest.fn(),
  });
  const storyState = clientStoryState({
    players: { player1: player(beats) },
    ...overrides,
  });
  return renderMarkup(
    <GameSessionContext.Provider value={gameSession(storyState)}>
      <StoryDisplay onChoiceSelected={jest.fn()} />
    </GameSessionContext.Provider>
  );
}

function expectNoteAbove(html: string, text: string, marker: string): void {
  const notes = notesIn(html);
  expect(notes).toEqual([
    expect.objectContaining({ name: "AI system", lang: "en", text }),
  ]);
  expect(html.indexOf(marker)).toBeGreaterThan(notes[0]?.offset ?? Infinity);
}

describe("StoryDisplay AI notice", () => {
  it("shows the session notice while the first beat is being written", () => {
    const html = renderStory([], null);

    expect(notesIn(html)).toEqual([
      expect.objectContaining({ name: "AI system", lang: "en", text: SESSION }),
    ]);
  });

  it("shows the session notice above the first beat, on the first paint and once the beat is picked", () => {
    const beats = [beat("Arrival", -1)];

    expectNoteAbove(renderStory(beats, null), SESSION, "[beat: none]");
    expectNoteAbove(renderStory(beats, 0), SESSION, "[beat: Arrival]");
  });

  it("shows the session notice above the beat a returning player resumes on", () => {
    const beats = [beat("Arrival"), beat("Crossroads"), beat("The Pier", -1)];

    expectNoteAbove(renderStory(beats, 2), SESSION, "[beat: The Pier]");
  });

  it("shows the session notice above the next beat when a returning player's choice is still being written", () => {
    const beats = [beat("Arrival"), beat("Crossroads")];

    expectNoteAbove(
      renderStory(beats, 2),
      SESSION,
      "[next beat is being written]"
    );
  });

  it("shows the child-friendly notice instead in read-with-kids stories", () => {
    const html = renderStory([beat("Bedtime", -1)], 0, {
      category: "read-with-kids",
    });

    expectNoteAbove(html, KIDS, "[beat: Bedtime]");
  });

  // The session opened while beat 4 was being written; the player looks back
  const threads = [
    beat("Arrival"),
    beat("The Night Market (1/2)"),
    beat("The Night Market (2/2)"),
    beat("The Old Mill (1/2)"),
  ];

  it.each(["vent-about-reality", "see-your-future-self"] as const)(
    "reminds above the first beat of each Thread in %s stories",
    (category) => {
      expectNoteAbove(
        renderStory(threads, 1, { category }),
        REMINDER,
        "[beat: The Night Market (1/2)]"
      );
      expectNoteAbove(
        renderStory(threads, 3, { category }),
        REMINDER,
        "[beat: The Old Mill (1/2)]"
      );
      expect(notesIn(renderStory(threads, 2, { category }))).toEqual([]);
    }
  );

  it("shows no notice on later beats of other stories", () => {
    for (const category of ["enjoy-fiction", "read-with-kids"] as const) {
      expect(notesIn(renderStory(threads, 1, { category }))).toEqual([]);
    }
  });
});
