import type { GameAiNoticeVariant } from "game/utils/aiNotice";

/*
 * The in-game notice that an AI writes the story (AI Act Art. 50(1)).
 * NOT MOUNTED. The wording below is the proposal from the AI Act assessment
 * of 2026-09-25 (§5 D1) and is under the owner's review; mount the component
 * only with the approved copy. Pick the variant with gameAiNoticeVariant and
 * useThreadChangeReminder. It renders on every page load and has no "dismiss
 * forever": the conservative reading asks for a notice in every session.
 */

const NOTICE_TEXT: Record<GameAiNoticeVariant, string> = {
  default:
    "Story text and images in this game are generated by AI as you play.",
  kids: "This story is written by an AI. That's a computer program, not a real person. It can make mistakes.",
  reminder:
    "Reminder: this story is generated by an AI system, not written by a person.",
};

type GameAiNoticeProps = {
  variant: GameAiNoticeVariant;
  className?: string;
};

export function GameAiNotice({ variant, className = "" }: GameAiNoticeProps) {
  return (
    <p
      role="note"
      lang="en"
      className={`flex items-start gap-2 text-sm text-primary-600 ${className}`}
    >
      <span
        aria-hidden="true"
        className="rounded border border-primary-200 px-1 text-xs font-semibold text-primary-700"
      >
        AI
      </span>
      <span>{NOTICE_TEXT[variant]}</span>
    </p>
  );
}
